name: Update token every 10 min

on:
  schedule:
    - cron: "*/3 * * * *"       # every 10 minutes
  workflow_dispatch:             # allow manual run for testing
  
permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate token
        run: |
          python3 - <<'PY'
          from datetime import datetime, timezone
          import math

          A = 73      # your secret multiplier
          B = 417     # your secret offset

          slot = int(datetime.now(timezone.utc).timestamp()) // 600   # 10-minute slot
          token = (slot * A + B) % 1_000_000

          with open("token.txt", "w") as f:
              f.write(str(token) + "\n")
          PY

      - name: Commit & push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add token.txt
          git commit -m "update token" || echo "No changes to commit"
          git push
