name: Update token every 10 min

on:
  schedule:
    - cron: "*/2 * * * *"      # alle 10 Minuten
  workflow_dispatch:            # manuell startbar

permissions:
  contents: write               # erlaubt Commit & Push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate token
        run: |
          python3 - <<'PY'
          from datetime import datetime, timezone
          A = 73        # geheimer Faktor
          B = 417       # geheimer Offset

          slot = int(datetime.now(timezone.utc).timestamp()) // 600  # 10-min Slot
          token = (slot * A + B) % 1_000_000

          with open("token.txt", "w") as f:
              f.write(str(token) + "\n")
          PY

      - name: Commit & push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add token.txt
          git commit -m "update token" || echo "No changes to commit"
          git push
